# Generated by Django 5.2 on 2025-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(related_name='participant', through='events.EventParticipant', to='events.event'),
        ),
    ]
